packages:
  - packages/*
  - workspace
autoInstallPeers: true
linkWorkspacePackages: true
lockfileIncludeTarballUrl: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - node-pty
  - nx
  - protobufjs
  - unrs-resolver
  - yarn
peerDependencyRules:
  allowedVersions:
    '@shopify/cli-hydrogen>@graphql-codegen/cli': 6.0.1
    '@shopify/polaris>react': 19.2.4
    '@shopify/polaris>react-dom': 19.2.4
    'react-dom>react': 18.3.1
    'use-resize-observer>react-dom': 19.2.4
publicHoistPattern:
  - '*vitest*'
  - '*vite*'
  - '*eslint*'
  - '*prettier*'
strictPeerDependencies: false
